/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ocr_java */

#ifndef _Included_com_ocr_java
#define _Included_com_ocr_java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ocr_java
 * Method:    getOcrArray
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ocr_1java_getOcrArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ocr_java
 * Method:    setOcrArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_ocr_1java_setOcrArray
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
